### ISSUE TITLE
What versions of Theano and Lasagne should I use?

### ISSUE THREAD

**Issue by hugochan** [rdevon/BGAN#1]
Hi,

I had trouble running the mnist example, which raised the following error: ImportError: cannot import name 'downsample'.

Could you please clarify what versions of Theano and Lasagne should I use to be able to run the example?

Thank you!
Hugo

**Comment by rdevon** [comment]
Hi, yes you should use the "bleeding edge" for both.  In fact, you can follow the "bleeding edge" instructions for Lasagne for both:
http://lasagne.readthedocs.io/en/latest/user/installation.html

Let me know if you still have issues.

**Comment by hugochan** [comment]
Sorry for the late reply. It works now!

**Comment by rdevon** [comment]
Great!
